mode = "dark"

accent = "#6fa7bb"
selection = "#373d46"
muted = "#4d545e"
background = "#212429"
dark_background = "#1a1d20"
darker_background = "#111315"
lighter_background = "#2f343a"
foreground = "#c0c7d0"
dark_foreground = "#646d7a"
light_foreground = "#969ea9"
bright_foreground = "#dce1e7"
red = "#b26466"
yellow = "#b1a06f"
orange = "#b58061"
green = "#71a589"
cyan = "#6da7a9"
blue = "#6fa7bb"
magenta = "#a8789b"
brown = "#805c45"
bright_red = "#bd787a"
bright_yellow = "#bcad83"
bright_green = "#84b099"
bright_cyan = "#80b3b4"
bright_blue = "#84b4c5"
bright_magenta = "#b48aa9"
